services:
  mysql:
    image: mysql:8.0
    container_name: myshop-mysql

    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: myshop_manager

    ports:
      - "3306:3306"

    volumes:
      - myshop-mysql-data:/var/lib/mysql

  prometheus:
    image: prom/prometheus:latest
    container_name: myshop-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: myshop-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana-data:/var/lib/grafana

volumes:
  myshop-mysql-data:
  prometheus-data:
  grafana-data:
