global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'myshop-module-manager'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:1122'

  - job_name: 'myshop-media-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:8081'

  - job_name: 'myshop-media-worker'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:8082'

  - job_name: 'node'
    static_configs:
      - targets:
          - 'node-exporter:9100'
